/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author USUARIO
 */
public class menugeneral extends javax.swing.JFrame {
        private ventana_articulo mov = new ventana_articulo ();
        private ventana_empleado mov1= new ventana_empleado ();
        private ventana_cita mov3= new ventana_cita ();
        private ventana_clientes mov4= new ventana_clientes ();

    /**
     * Creates new form menugeneral
     */
    public menugeneral() {
        initComponents();
        inicio();
            }
    private void inicio(){
        ifCuenta.setContentPane(mov);
        mov.setSize(600,600);
        ifCuenta.setSize(600,600);
     ifempleados.setContentPane(mov1);
        mov1.setSize(700,700);
        ifempleados.setSize(700,700);
       ifcita.setContentPane(mov3);
        mov3.setSize(700,700);
        ifcita.setSize(700,700);
        ifclientes.setContentPane(mov4);
        mov4.setSize(700,700);
        ifclientes.setSize(700,700);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        escritorio = new javax.swing.JPanel();
        ifempleado = new javax.swing.JInternalFrame();
        jclientes = new javax.swing.JDesktopPane();
        ifCuenta = new javax.swing.JInternalFrame();
        jiCliente = new javax.swing.JInternalFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        ifempleados = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        ifcita = new javax.swing.JInternalFrame();
        ifclientes = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        openventas = new javax.swing.JMenuItem();
        openempleados = new javax.swing.JMenuItem();
        openvehiculo = new javax.swing.JMenuItem();
        openarticulos = new javax.swing.JMenuItem();
        opencitas = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        ifempleado.setVisible(true);

        javax.swing.GroupLayout ifempleadoLayout = new javax.swing.GroupLayout(ifempleado.getContentPane());
        ifempleado.getContentPane().setLayout(ifempleadoLayout);
        ifempleadoLayout.setHorizontalGroup(
            ifempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifempleadoLayout.setVerticalGroup(
            ifempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jclientes.setBackground(new java.awt.Color(204, 204, 204));

        ifCuenta.setVisible(false);

        javax.swing.GroupLayout ifCuentaLayout = new javax.swing.GroupLayout(ifCuenta.getContentPane());
        ifCuenta.getContentPane().setLayout(ifCuentaLayout);
        ifCuentaLayout.setHorizontalGroup(
            ifCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        ifCuentaLayout.setVerticalGroup(
            ifCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        jclientes.add(ifCuenta);
        ifCuenta.setBounds(100, 30, 220, 210);

        jiCliente.setVisible(false);

        javax.swing.GroupLayout jiClienteLayout = new javax.swing.GroupLayout(jiCliente.getContentPane());
        jiCliente.getContentPane().setLayout(jiClienteLayout);
        jiClienteLayout.setHorizontalGroup(
            jiClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jiClienteLayout.setVerticalGroup(
            jiClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(jiCliente);
        jiCliente.setBounds(100, 270, 280, 250);

        jInternalFrame1.setVisible(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(jInternalFrame1);
        jInternalFrame1.setBounds(350, 40, 240, 210);

        ifempleados.setVisible(false);
        ifempleados.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                ifempleadosInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout ifempleadosLayout = new javax.swing.GroupLayout(ifempleados.getContentPane());
        ifempleados.getContentPane().setLayout(ifempleadosLayout);
        ifempleadosLayout.setHorizontalGroup(
            ifempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifempleadosLayout.setVerticalGroup(
            ifempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(ifempleados);
        ifempleados.setBounds(0, 0, 50, 36);

        jInternalFrame2.setVisible(false);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 28, 36);

        ifcita.setVisible(false);

        javax.swing.GroupLayout ifcitaLayout = new javax.swing.GroupLayout(ifcita.getContentPane());
        ifcita.getContentPane().setLayout(ifcitaLayout);
        ifcitaLayout.setHorizontalGroup(
            ifcitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifcitaLayout.setVerticalGroup(
            ifcitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(ifcita);
        ifcita.setBounds(0, 0, 280, 210);
        ifcita.getAccessibleContext().setAccessibleDescription("");

        ifclientes.setVisible(true);
        ifclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ifclientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ifclientesLayout = new javax.swing.GroupLayout(ifclientes.getContentPane());
        ifclientes.getContentPane().setLayout(ifclientesLayout);
        ifclientesLayout.setHorizontalGroup(
            ifclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifclientesLayout.setVerticalGroup(
            ifclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jclientes.add(ifclientes);
        ifclientes.setBounds(0, 0, 28, 36);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Catalogos");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cliente");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        openventas.setMnemonic('s');
        openventas.setText("Ventas");
        openventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openventasActionPerformed(evt);
            }
        });
        fileMenu.add(openventas);

        openempleados.setText("Empleados");
        openempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openempleadosActionPerformed(evt);
            }
        });
        fileMenu.add(openempleados);

        openvehiculo.setText("Vehiculo");
        openvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openvehiculoActionPerformed(evt);
            }
        });
        fileMenu.add(openvehiculo);

        openarticulos.setText("Articulos");
        openarticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openarticulosActionPerformed(evt);
            }
        });
        fileMenu.add(openarticulos);

        opencitas.setText("Citas");
        opencitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opencitasActionPerformed(evt);
            }
        });
        fileMenu.add(opencitas);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        //ifCuenta.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openventasActionPerformed

    private void openvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openvehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openvehiculoActionPerformed

    private void openempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openempleadosActionPerformed
        ifempleados.setVisible(true);
    }//GEN-LAST:event_openempleadosActionPerformed

    private void opencitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opencitasActionPerformed
        ifcita.setVisible(true);
    }//GEN-LAST:event_opencitasActionPerformed

    private void openarticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openarticulosActionPerformed
        ifCuenta.setVisible(true);
    }//GEN-LAST:event_openarticulosActionPerformed

    private void ifempleadosInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_ifempleadosInternalFrameActivated
        
    }//GEN-LAST:event_ifempleadosInternalFrameActivated

    private void ifclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ifclientesMouseClicked
        ifclientes.setVisible(true);
    }//GEN-LAST:event_ifclientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */  
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break; 
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menugeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menugeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menugeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menugeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menugeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    public static javax.swing.JInternalFrame ifCuenta;
    public static javax.swing.JInternalFrame ifcita;
    public static javax.swing.JInternalFrame ifclientes;
    public static javax.swing.JInternalFrame ifempleado;
    public static javax.swing.JInternalFrame ifempleados;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JDesktopPane jclientes;
    private javax.swing.JInternalFrame jiCliente;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openarticulos;
    private javax.swing.JMenuItem opencitas;
    private javax.swing.JMenuItem openempleados;
    private javax.swing.JMenuItem openvehiculo;
    private javax.swing.JMenuItem openventas;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables
}
